--vim.opt.filetype = 'format on'

vim.opt.compatible = false
vim.opt.syntax = 'enable'
vim.opt.autoread = true
vim.opt.autoindent = true
vim.opt.backspace = { 'indent','eol','start' }
vim.opt.cmdheight = 1
vim.opt.cursorline = true
vim.opt.encoding = 'UTF-8'
vim.opt.foldmethod = 'syntax'
vim.opt.foldenable = false
vim.opt.hidden = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
-- vim.opt.lazyredraw = true
vim.opt.modifiable = true
vim.opt.mouse = 'a'
vim.opt.backup  = false
vim.opt.swapfile   = false
vim.opt.wb    = false
vim.opt.wrap             = false
vim.opt.relativenumber = true
vim.opt.rnu = true
vim.opt.showmatch = true
vim.opt.signcolumn = 'yes'
vim.opt.so = 7
vim.opt.splitright = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.expandtab = true
vim.opt.termguicolors = true
vim.opt.updatetime = 300
vim.opt.wildmenu = true
