vim.keymap.set("n", "]g", vim.diagnostic.goto_next, { noremap = true, silent = true })
vim.keymap.set("n", "[g", vim.diagnostic.goto_prev, { noremap = true, silent = true })
-- vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, { noremap = true, silent = true })
vim.keymap.set("n", "<space>rn", vim.lsp.buf.rename, { noremap = true, silent = true })
-- vim.keymap.set("n", "<leader>ac", vim.lsp.buf.code_action, { noremap = true, silent = true })
vim.keymap.set("n", "<space>ca", vim.lsp.buf.code_action, { noremap = true, silent = true })
vim.keymap.set("n", "<space>ff", vim.lsp.buf.format, { noremap = true, silent = true })

-- nmap <leader>qf  <Plug>(coc-fix-current)
-- xmap if <Plug>(coc-funcobj-i)
-- omap if <Plug>(coc-funcobj-i)
-- xmap af <Plug>(coc-funcobj-a)
-- omap af <Plug>(coc-funcobj-a)
-- xmap ic <Plug>(coc-classobj-i)
-- omap ic <Plug>(coc-classobj-i)
-- xmap ac <Plug>(coc-classobj-a)
-- omap ac <Plug>(coc-classobj-a)
-- nmap <silent> <C-s> <Plug>(coc-range-select)
-- xmap <silent> <C-s> <Plug>(coc-range-select)

