return {}
-- return {
--   "nvim-lualine/lualine.nvim",
--   dependencies = { "nvim-tree/nvim-web-devicons" },
--   config = function()
--     require("lualine").setup({
--       options = {
--         always_show_tabline = true,
--         always_show_winbar = true,
--         -- theme = "onedark",
--         disabled_filetypes = {
--           "NvimTree",
--           "trouble",
--           "TelescopePrompt",
--         },
--         tabline = {
--           lualine_a = { "buffers" },
--           lualine_b = { "branch" },
--           lualine_c = { "filename" },
--           lualine_x = {},
--           lualine_y = {},
--           lualine_z = { "tabs" },
--         },
--         winbar = {
--           lualine_a = {
--             { filepath },
--           },
--         },
--         inactive_winbar = {
--           lualine_a = {
--             { filepath },
--           },
--         },
--       },
--     })
--
--     vim.opt.showtabline = 1
--   end,
-- }
